spring:
  application:
    name: hs-spring-content-creation

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    schemas: content_creation
    createSchemas: true
    baselineOnMigrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
