spring:
  application:
    name: api-gateway

contentCreationUrl: ${CONTENT_CREATION_URL:http://localhost:8081}
moderationUrl: ${MODERATION_URL:http://localhost:8082}
distributionUrl: ${DISTRIBUTION_URL:http://localhost:8083}
