apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-test
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  instances: 1

  managed:
    roles:
      - name: k8s-user
        ensure: present
        login: true
        superuser: false
        inRoles:
          - pg_monitor
          - pg_signal_backend
        passwordSecret:
          name: cluster-example-dante

  bootstrap:
    initdb:
      database: test-db

  storage:
    size: 64Mi

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "250m"
