apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.clusterName }}-creds
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.database.username | trim | b64enc }}
  password: {{ .Values.database.password | trim | b64enc }}
