spring:
  application:
    name: hs-spring-moderation

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/test_db}
    username: ${POSTGRES_USERNAME:user}
    password: ${POSTGRES_PASSWORD:pass}

  flyway:
    enabled: true
    schemas: moderation
    createSchemas: true
    baselineOnMigrate: true
    locations: classpath:db/migration

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  threads:
    virtual:
      enabled: false

server:
  servlet:
    contextPath: /api
