spring:
  application:
    name: hs-spring-moderation

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    schemas: moderation
    createSchemas: true
    baselineOnMigrate: true
    locations: classpath:db/migration
    check-location: true

  jpa:
    hibernate:
      ddl-auto: validate
