spring:
  application:
    name: hs-spring-distribution

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    schemas: distribution
    createSchemas: true
    baselineOnMigrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
