spring:
  application:
    name: hs-spring-distribution

  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: user
    password: pass

  flyway:
    enabled: true
    schemas: distribution
    createSchemas: true
    baselineOnMigrate: true
    locations: classpath:db/migration

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  threads:
    virtual:
      enabled: false

server:
  servlet:
    contextPath: /api
  port: 8083

kafka:
  bootstrap-servers: localhost:9092
  topic: hs-spring
  group-id: Distribution
  trustedPackages: com.yatskevich.hs.spring.content_creation.api_client.dto
