apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rk-common.fullname" . }}-config
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ required "'appConfig.spring.datasource.url' parameter is required" $.Values.appConfig.spring.datasource.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ required "'appConfig.spring.datasource.username' parameter is required" $.Values.appConfig.spring.datasource.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ required "'appConfig.spring.datasource.password' parameter is required" $.Values.appConfig.spring.datasource.password | quote }}
  SPRING_THREADS_VIRTUAL_ENABLED: {{ default "false" $.Values.appConfig.spring.threads.virtual.enabled | quote }}
  SERVER_PORT: {{ default "8080" $.Values.appConfig.server.port | quote }}
  {{- if $.Values.appConfig.logging.level.com.yatskevich }}
  LOGGING_LEVEL_COM_YATSKEVICH: {{ $.Values.appConfig.logging.level.com.yatskevich | quote }}
  {{- end }}
  {{- if $.Values.appConfig.kafka.bootstrapServers }}
  KAFKA_BOOTSTRAPSERVERS: {{ $.Values.appConfig.kafka.bootstrapServers | quote }}
  {{- end }}
