apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "my-chart.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{ - include "my-chart.labels" . | nindent 8 }}
        {{ - with .Values.podLabels }}
        {{ - toYaml . | nindent 8 }}
        {{ - end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName . }}
      {{- end }}
      restartPolicy: {{ default "Always" .Values.restartPolicy }}
      containers:
      {{ include "rk-common.name" . }}
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          http
              containerPort: {{ default "8080" .Values.container.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "rk-common.fullname" . }}-config
#          env:
#          SPRING_DATASOURCE_URL
#              value: {{ $.Values.appConfig.spring.datasource.url | quote }}
#          SPRING_DATASOURCE_USERNAME
#              value: {{ $.Values.appConfig.spring.datasource.username | quote }}
#          SPRING_DATASOURCE_PASSWORD
#              value: {{ $.Values.appConfig.spring.datasource.password | quote }}
#          SPRING_THREADS_VIRTUAL_ENABLED
#              value: {{ default "false" $.Values.appConfig.spring.threads.virtual.enabled | quote }}
#          SERVER_PORT
#              value: {{ default "8080" $.Values.appConfig.server.port | quote }}
#            {{- if $.Values.appConfig.logging.level.com.yatskevich }}
#          LOGGING_LEVEL_COM_YATSKEVICH
#              value: {{ $.Values.appConfig.logging.level.com.yatskevich | quote }}
#            {{- end }}
#            {{- if $.Values.appConfig.kafka.bootstrapServers }}
#          KAFKA_BOOTSTRAPSERVERS
#              value: {{ $.Values.appConfig.kafka.bootstrapServers | quote  }
#            {{ - end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
