#apiVersion: v1
#data:
#  password: azhzLXBhc3N3b3Jk
#  username: azhzLXVzZXI=
#kind: Secret
#metadata:
#  name: database-user
#type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-second
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  instances: 1

  bootstrap:
    initdb:
      database: test-db
#      owner: k8s-user
#      secret:
#        name: database-user

  storage:
    size: 64Mi

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "250m"
